[2025-05-07T20:38:03.522+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: cv_processing_pipeline.extract_pdfs manual__2025-05-07T20:38:02.206246+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
